import type { CtnSyntaxProfile } from "./types";

export const defaultCtnSyntaxProfile = {
  name: "默认 CTN 语法",
  tabDisplayWidth: 4,
  titleRule: {
    type: "title",
    label: "标题",
    textColor: "cyan",
    tone: "blue",
  },
  conceptRule: {
    type: "concept",
    label: "顶格概念",
    textColor: "cyan",
    tone: "blue",
  },
  markerRules: [
    {
      marker: "```",
      type: "multiline-block",
      label: "多行块",
      role: "multiline",
      textColor: "green",
      tone: "gray",
    },
    {
      marker: ":",
      type: "definition",
      label: "定义",
      role: "normal",
      textColor: "teal",
      tone: "green",
    },
    {
      marker: ">",
      type: "personal-understanding",
      label: "理解",
      role: "normal",
      textColor: "violet",
      tone: "violet",
    },
    {
      marker: "-",
      type: "component",
      label: "组分",
      role: "normal",
      textColor: "blue",
      tone: "blue",
    },
  ],
  inlineRules: [
    {
      close: "]]",
      kind: "paired",
      label: "全局概念引用",
      open: "[[",
      textColor: "cyan",
      tone: "blue",
      type: "global-reference",
    },
    {
      close: "`",
      kind: "paired",
      label: "行内代码",
      open: "`",
      textColor: "green",
      tone: "green",
      type: "inline-code",
    },
    {
      close: ">",
      kind: "paired",
      label: "局部概念引用",
      open: "<",
      textColor: "teal",
      tone: "teal",
      type: "local-reference",
    },
    {
      kind: "single",
      label: "并列分隔",
      marker: "\\",
      textColor: "amber",
      tone: "amber",
      type: "parallel-separator",
    },
  ],
} satisfies CtnSyntaxProfile;
