// SPDX-License-Identifier: GPL-3.0-or-later

// The sole source of shared presentation values. No DOM or business dependencies.
export const designMetrics = {
  rowHeight: 28,
  gap: 8,
  tightGap: 4,
  panelPadding: 12,
  sectionGap: 16,
  headerHeight: 40,
  toolbarHeight: 36,
  treeIndent: 14,
  context: { default: 280, min: 220, max: 420 },
  detail: { default: 320, min: 240, max: 500, narrowMinHeight: 200 },
  problems: { default: 200, min: 120, max: 360 },
  resizeKeyboardStep: 16,
  resizeHitSize: 10,
  form: { maxWidth: 720, labelWidth: 128, compactLabelWidth: 72 },
  propertyLabelWidth: 88,
  input: { minWidth: 72, maxWidth: 320 },
  rangeValueWidth: 44,
  popover: { width: 320, compactWidth: 224 },
  quickPick: { width: 520, maxListHeight: 320 },
  contextMenuMinWidth: 140,
} as const;

// Expanded by the CSS adapter; browsers cannot use custom properties in queries.
export const designBreakpoints = {
  workbench: 1120,
  repository: 720,
  form: 360,
} as const;

const px = (value: number) => `${value}px`;

export const designTokens = {
  "--font-ui": "system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", \"Noto Sans CJK SC\", \"Source Han Sans SC\", \"Microsoft YaHei UI\", sans-serif",
  "--font-code": "\"Cascadia Code\", \"SFMono-Regular\", Consolas, \"Noto Sans Mono CJK SC\", monospace",
  "--color-activity": "#181818",
  "--color-context": "#181818",
  "--color-editor": "#1f1f1f",
  "--color-panel": "#181818",
  "--color-panel-strong": "#313131",
  "--color-input": "#313131",
  "--color-hover": "#2a2d2e",
  "--color-selected": "#37373d",
  "--color-selection-hover": "#2c2c2c",
  "--color-selection-active": "#3b3b3b",
  "--color-selection-active-hover": "#454545",
  "--color-border": "#2b2b2b",
  "--color-border-strong": "#3c3c3c",
  "--color-fg": "#cccccc",
  "--color-fg-strong": "#ffffff",
  "--color-fg-muted": "#9d9d9d",
  "--color-fg-subtle": "#6f6f6f",
  "--color-fg-disabled": "#6a6a6a",
  "--color-accent": "#0078d4",
  "--color-accent-soft": "rgba(0, 120, 212, 0.18)",
  "--color-accent-subtle": "rgba(0, 120, 212, 0.08)",
  "--color-button": "#0078d4",
  "--color-button-hover": "#026ec1",
  "--color-content-accent": "#007acc",
  "--color-content-accent-subtle": "rgba(0, 122, 204, 0.08)",
  "--color-link": "#569cd6",
  "--color-error": "#f85149",
  "--color-warning": "#cca700",
  "--color-error-soft": "rgba(244, 135, 113, 0.12)",
  "--color-overlay": "rgba(0, 0, 0, 0.35)",
  "--color-success": "#6a9955",
  "--color-graph-edge": "rgba(86, 156, 214, 0.5)",
  "--shadow-float": "0 8px 24px rgba(0, 0, 0, 0.32)",
  "--ctn-tone-green": "#6a9955",
  "--ctn-tone-teal": "#4ec9b0",
  "--ctn-tone-cyan": "#9cdcfe",
  "--ctn-tone-blue": "#569cd6",
  "--ctn-tone-indigo": "#6796e6",
  "--ctn-tone-violet": "#c586c0",
  "--ctn-tone-pink": "#d16d9e",
  "--ctn-tone-red": "#f48771",
  "--ctn-tone-amber": "#d7ba7d",
  "--ctn-tone-gray": "#858585",
  "--ctn-tone-neutral": "#87938d",
  "--ctn-tone-green-soft": "rgba(106, 153, 85, 0.08)",
  "--ctn-tone-teal-soft": "rgba(78, 201, 176, 0.08)",
  "--ctn-tone-cyan-soft": "rgba(86, 156, 214, 0.08)",
  "--ctn-tone-blue-soft": "rgba(86, 156, 214, 0.08)",
  "--ctn-tone-indigo-soft": "rgba(100, 102, 149, 0.1)",
  "--ctn-tone-violet-soft": "rgba(197, 134, 192, 0.08)",
  "--ctn-tone-pink-soft": "rgba(197, 134, 192, 0.08)",
  "--ctn-tone-red-soft": "rgba(244, 135, 113, 0.09)",
  "--ctn-tone-amber-soft": "rgba(206, 145, 120, 0.08)",
  "--ctn-tone-gray-soft": "rgba(128, 128, 128, 0.08)",
  "--app-activity-width": "48px",
  "--app-context-width": px(designMetrics.context.default),
  "--app-detail-width": px(designMetrics.detail.default),
  "--app-detail-collapsed-width": "36px",
  "--app-main-min-width": "420px",
  "--app-status-bar-height": "var(--ui-row-height)",
  "--app-problems-height": px(designMetrics.problems.default),
  "--ui-border-width": "1px",
  "--ui-panel-padding": px(designMetrics.panelPadding),
  "--ui-panel-header-height": px(designMetrics.headerHeight),
  "--ui-gap": px(designMetrics.gap),
  "--ui-gap-tight": px(designMetrics.tightGap),
  "--ui-control-height": "var(--ui-row-height)",
  "--ui-section-gap": px(designMetrics.sectionGap),
  "--ui-toolbar-height": px(designMetrics.toolbarHeight),
  "--ui-popover-width": px(designMetrics.popover.width),
  "--ui-popover-compact-width": px(designMetrics.popover.compactWidth),
  "--ui-form-max-width": px(designMetrics.form.maxWidth),
  "--ui-action-icon-size": "16px",
  "--ui-activity-icon-size": "24px",
  "--ui-symbol-size": "13px",
  "--ui-row-height": px(designMetrics.rowHeight),
  "--ui-tree-indent": px(designMetrics.treeIndent),
  "--ui-radius": "6px",
  "--ui-selection-radius": "var(--ui-radius)",
  "--ui-focus-outline": "1px solid var(--color-accent)",
  "--ui-z-overlay": "100",
  "--ui-font-size": "13px",
  "--ui-line-height": "1.4",
  "--ui-body-weight": "400",
  "--ui-emphasis-weight": "600",
  "--ui-inline-symbol-line-height": "1",
  "--ui-numeric-font-variant": "tabular-nums",
  "--ctn-editor-font-size": "14px",
  "--ctn-editor-line-height": "1.5",
  "--app-context-min-width": px(designMetrics.context.min),
  "--app-context-max-width": px(designMetrics.context.max),
  "--app-detail-narrow-min-height": px(designMetrics.detail.narrowMinHeight),
  "--app-detail-min-width": px(designMetrics.detail.min),
  "--app-detail-max-width": px(designMetrics.detail.max),
  "--app-resize-hit-size": px(designMetrics.resizeHitSize),
  "--ui-form-label-width": px(designMetrics.form.labelWidth),
  "--ui-form-compact-label-width": px(designMetrics.form.compactLabelWidth),
  "--ui-property-label-width": px(designMetrics.propertyLabelWidth),
  "--ui-input-min-width": px(designMetrics.input.minWidth),
  "--ui-input-max-width": px(designMetrics.input.maxWidth),
  "--ui-range-value-width": px(designMetrics.rangeValueWidth),
  "--ui-quick-pick-width": px(designMetrics.quickPick.width),
  "--ui-quick-pick-list-height": px(designMetrics.quickPick.maxListHeight),
  "--ui-context-menu-min-width": px(designMetrics.contextMenuMinWidth),
} as const;
