// SPDX-License-Identifier: GPL-3.0-or-later

/**
 * API wire types are inferred from the runtime schemas. This compatibility-free
 * barrel keeps imports short without becoming a second contract owner.
 */
export {
  apiV1AutomationScopes,
  apiV1Scopes,
} from "./schemas.ts";
export type {
  ApiV1AuditEntryDto,
  ApiV1AuditPageDto,
  ApiV1BlockChangeDto,
  ApiV1CapabilitiesDto,
  ApiV1ChangeEventDto,
  ApiV1CheckpointEventDto,
  ApiV1CommandModeDto,
  ApiV1CommandOutcomeDto,
  ApiV1CommandResultDto,
  ApiV1CommittedCommandResultDto,
  ApiV1CreateTokenRequestDto,
  ApiV1CreatedTokenDto,
  ApiV1CtnBlockDto,
  ApiV1CtnDiagnosticDto,
  ApiV1CtnDocumentDto,
  ApiV1DomainChangeSetDto,
  ApiV1ErrorCodeDto,
  ApiV1ErrorDto,
  ApiV1EventDto,
  ApiV1JournalCommandDto,
  ApiV1JournalEntriesDto,
  ApiV1JournalEntrySummaryDto,
  ApiV1PrincipalDto,
  ApiV1PreviewCommandResultDto,
  ApiV1ResourceChangeDto,
  ApiV1ResourceVersionDto,
  ApiV1RevisionCheckpointDto,
  ApiV1Scope,
  ApiV1SearchFaultDto,
  ApiV1SearchRequestDto,
  ApiV1SearchResponseDto,
  ApiV1SearchResultDto,
  ApiV1SyntaxBlockRuleDto,
  ApiV1SyntaxGuideDto,
  ApiV1TextDiffHunkDto,
  ApiV1TodoCollectionDto,
  ApiV1TodoCollectionSummaryDto,
  ApiV1TodoCollectionsDto,
  ApiV1TodoCommandDto,
  ApiV1TodoItemStateDto,
  ApiV1TodoRecurrenceProjectionDto,
  ApiV1TokenDto,
  ApiV1WorkspaceCommandDto,
  ApiV1WorkspaceListDto,
  ApiV1WorkspaceSummaryDto,
  ApiV1WorkspaceTreeDto,
  ApiV1WorkspaceTreeNodeDto,
} from "./schemas.ts";
